### ISSUE TITLE
MacOS没安装mono的环境下提示错误

### ISSUE THREAD

**Issue by parkycai** [tylearymf/UniHacker#17]
在没有mono的机子上ApplyPatch的时候报错：
```
System.DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMonoPosixHelper, 0x0001): tried: 'libMonoPosixHelper' (no such file), '/usr/local/lib/libMonoPosixHelper' (no such file), '/usr/lib/libMonoPosixHelper' (no such file), '/Users/*****/libMonoPosixHelper' (no such file)
   at Mono.Unix.Native.Syscall.stat(String file_name, Stat& buf)
   at Mono.Unix.UnixFileSystemInfo.GetFileStatus(String path, Stat& stat)
   at Mono.Unix.UnixFileSystemInfo.Refresh(Boolean force)
   at Mono.Unix.UnixFileSystemInfo..ctor(String path)
   at Mono.Unix.UnixFileInfo..ctor(String path)
   at UniHacker.UnityPatcher.ApplyPatch(Action`1 progress) in /Users/*****/Documents/Workspaces/GitHub/UniHacker/Patcher/Unity/UnityPatcher.cs:line 64
   at UniHacker.Views.MainWindow.PatchBtn_Click(Object sender, RoutedEventArgs e) in /Users/*****/Documents/Workspaces/GitHub/UniHacker/Views/MainWindow.axaml.cs:line 84
```

看了对应的代码是
```
            if (PlatformUtils.IsOSX() || PlatformUtils.IsLinux())
            {
                _ = new UnixFileInfo(bakPath)
                {
                    // rwxr-xr-x
                    FileAccessPermissions = (FileAccessPermissions)0B111101101
                };
            }
```

这个是去掉x属性吗？看是否有其他方案来达成，或者可以直接删掉？（似乎注释掉也没事）

**Comment by tylearymf** [comment]
这个是给二进制文件加可执行权限的，不然就要手动用命令行搞一下

**Comment by parkycai** [comment]
> 这个是给二进制文件加可执行权限的，不然就要手动用命令行搞一下

要不走个命令行 `chmod +x` 好了？

**Comment by tylearymf** [comment]
> > 这个是给二进制文件加可执行权限的，不然就要手动用命令行搞一下
> 
> 要不走个命令行 `chmod +x` 好了？（或者直接注释掉……要恢复备份的就自己敲命令行+x吧……

那晚点我注释掉吧，之前我用来测试流程才加的
