### ISSUE TITLE
请问hub可以用，但是unity无法使用要怎么处理呢？

### ISSUE THREAD

**Issue by MarkSenCN** [tylearymf/UniHacker#51]
![WeChate862148b5c8b83d622734936bd279f89](https://user-images.githubusercontent.com/34280638/187481817-7a5a355c-4609-48cd-8e62-e87f83c22e32.png)
用源码运行提示这里的错误，如果下载你打包好的选择unity后就直接闪退了，请问是我这边权限没处理好吗？

**Comment by MarkSenCN** [comment]
测试了2019.1 2019.2 2019.3 2020.1都是这样

**Comment by tylearymf** [comment]
@MarkSenCN 需要管理员权限运行

**Comment by MarkSenCN** [comment]
> @MarkSenCN 需要管理员权限运行

忘了说我是mac的环境,用代码运行一开始是说要管理员权限,但是运行直接下载的app是没有提示这个权限的,但是直接闪退,unity和文件夹我都是给了最高权限,不知道是不是没搞对

**Comment by tylearymf** [comment]
> 

你下载的是哪里的app，是不是没下对

**Comment by MarkSenCN** [comment]
> 你下载的是哪里的app，是不是没下对

我又换了台mac试了下还是运行app,会让输入密码,然后选择unity.app就会崩溃闪退,你看我要把错误日志贴上来吗?

**Comment by tylearymf** [comment]
> 

可以，把日志贴上来吧，输密码那段就是获取管理员权限的，那应该是代码哪里有逻辑问题了

**Comment by MarkSenCN** [comment]
> 可以，把日志贴上来吧，输密码那段就是获取管理员权限的，那应该是代码哪里有逻辑问题了

[errorlog.txt](https://github.com/tylearymf/UniHacker/files/9458136/errorlog.txt)
有点多我放文件里了

**Comment by tylearymf** [comment]
@MarkSenCN 你按下面的操作下，可以拿到运行时的代码异常日志，上面那个日志看不了是哪里有问题
1、拷贝 UniHackV3.3.app/Contents/Resources/script 到 你的桌面路径/script
2、然后执行下 chmod +x 你的桌面路径/script
3、sudo 你的桌面路径/script
4、然后出现崩溃后，会在窗口里面显示堆栈信息

**Comment by MarkSenCN** [comment]
> @MarkSenCN 你按下面的操作下，可以拿到运行时的代码异常日志，上面那个日志看不了是哪里有问题 1、拷贝 UniHackV3.3.app/Contents/Resources/ 到 你的桌面路径/Resources 2、然后执行下 chmod +x 你的桌面路径/Resources/script 3、sudo 你的桌面路径/Resources/script 4、然后出现崩溃后，会在窗口里面显示堆栈信息

<img width="620" alt="截屏2022-08-31 11 39 11" src="https://user-images.githubusercontent.com/34280638/187587544-c5a6e01a-e906-483d-92f8-17c140e09f78.png">

[script.zip](https://github.com/tylearymf/UniHacker/files/9458239/script.zip)
报错了，我把script文件传上来吧

**Comment by MarkSenCN** [comment]
> @MarkSenCN 你按下面的操作下，可以拿到运行时的代码异常日志，上面那个日志看不了是哪里有问题 1、拷贝 UniHackV3.3.app/Contents/Resources/ 到 你的桌面路径/Resources 2、然后执行下 chmod +x 你的桌面路径/Resources/script 3、sudo 你的桌面路径/Resources/script 4、然后出现崩溃后，会在窗口里面显示堆栈信息

Unhandled exception. System.UnauthorizedAccessException: Access to the path '/Applications/Unity/Hub/Editor/2019.3.15f1/Unity.app' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at UniHacker.UnityPatcher..ctor(String filePath)
   at UniHacker.PatchManager.GetPatcher(String filePath, PlatformType platformType)
   at UniHacker.Views.MainWindow.UpdateFilePath(String filePath)
   at UniHacker.Views.MainWindow.SelectBtn_Click(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 181
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4337
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UniHacker.Program.Main(String[] args)
zsh: abort      sudo /Users/mac/Desktop/Resources/script
mac@yangsendeMacBook-Pro unityproject % 

拿到了

**Comment by tylearymf** [comment]
奇怪，还是提示没权限访问这个目录 /Applications/Unity/Hub/Editor/2019.3.15f1/Unity.app

**Comment by MarkSenCN** [comment]
> 奇怪，还是提示没权限访问这个目录 /Applications/Unity/Hub/Editor/2019.3.15f1/Unity.app

我昨天试过把unity.app复制到桌面来运行也是报错

**Comment by tylearymf** [comment]
@MarkSenCN 那你试下 sudo chmod -R 777 你的桌面路径/Resources

**Comment by MarkSenCN** [comment]
> sudo chmod -R 777

不好意思，刚才下班去吃饭了，我给resource和unity都给了权限，用sudo chmod -R 777，但是还是提示这个错误闪退

**Comment by tylearymf** [comment]
> > sudo chmod -R 777
> 
> 不好意思，刚才下班去吃饭了，我给resource和unity都给了权限，用sudo chmod -R 777，但是还是提示这个错误闪退

那这个要查下了，我之前测试的时候是可以跑的

**Comment by MarkSenCN** [comment]
> 那这个要查下了，我之前测试的时候是可以跑的

麻烦了，如果你有空查的时候可以加下我qq或者微信，我给你提供远程连接，不过现在公司电脑没最新的vs得晚上回家才行不知道到时候你方便吗，我的qq是309269589，微信是loveless_ys
