### ISSUE TITLE
点击登录没反应问题

### ISSUE THREAD

**Issue by youZhuang** [tylearymf/UniHacker#99]
请教一下，这种登录问题能解决吗？下面是hub的日志
`{"timestamp":"2022-12-04T15:04:03.873Z","level":"info","moduleName":"Authentification Service","message":"[ 'Fetching user info from the identity provider using access token' ]"}
{"timestamp":"2022-12-04T15:04:03.873Z","level":"error","moduleName":"Authentification Service","message":"[\n  \"Error fetching user info from Access Token: TypeError: Cannot read property 'expiration' of null\"\n]"}
{"timestamp":"2022-12-04T15:04:03.874Z","level":"error","moduleName":"FeatureFlagsService","message":"[\n  'Invalid user specified. Please see https://docs.launchdarkly.com/docs/js-sdk-reference#initializing-the-client for instructions on SDK initialization.'\n]"}
{"timestamp":"2022-12-04T15:04:03.874Z","level":"error","moduleName":"FeatureFlagsService","message":"[\n  'Problem identifying user',\n  t [LaunchDarklyInvalidUserError]: Invalid user specified. Please see https://docs.launchdarkly.com/docs/js-sdk-reference#initializing-the-client for instructions on SDK initialization.\n      at Object.UserValidator.e.validateUser (/Applications/Unity Hub.app/Contents/Resources/app/node_modules/launchdarkly-js-sdk-common/dist/ldclient-common.cjs.js:1:23696)\n      at /Applications/Unity Hub.app/Contents/Resources/app/node_modules/launchdarkly-js-sdk-common/dist/ldclient-common.cjs.js:1:35527\n      at processTicksAndRejections (internal/process/task_queues.js:93:5) {\n    code: undefined\n  }\n]"}
{"timestamp":"2022-12-04T15:04:03.874Z","level":"info","moduleName":"FeatureFlagsService","message":"[ 'Set identity to', undefined ]"}
{"timestamp":"2022-12-04T15:04:03.875Z","level":"error","message":"Unhandled promise rejection, reason: Cannot read property 'expiration' of null\n\tstack TypeError: Cannot read property 'expiration' of null\n    at Object.monitorTokens (/Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:278:50)\n    at Object.<anonymous> (/Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:193:22)\n    at Generator.next (<anonymous>)\n    at /Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:4:12)\n    at Object.logInWithAccessToken (/Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:187:16)\n    at Object.openSignIn (/Applications/Unity Hub.app/Contents/Resources/app/build/main/services/authService/AuthService.js:165:14)\n    at click (/Applications/Unity Hub.app/Contents/Resources/app/build/main/appComponents/trayMenu/trayMenuData.js:56:35)\n    at MenuItem.click (electron/js2c/browser_init.js:73:1742)"}
{"timestamp":"2022-12-04T15:04:47.294Z","level":"info","moduleName":"RestEventRouter","message":"[ 'unsubscribing from: project.opened' ]"}`

**Comment by tylearymf** [comment]
@youZhuang 破解Hub的时候你是不是选了不需要登录自己的账号？

**Comment by youZhuang** [comment]
有可能 我重新破解试试
